#!/bin/bash

set -euo pipefail

## Variables
DISK="/dev/nvme0n1"
HOSTNAME="Arch"
## Functions

cecho() {
  GREEN='\033[0;32m'
  NC='\033[0m'
  echo -e "${GREEN}=== $1 ===${NC}"
}

arch_install_before_chroot() {

  cecho "Install Arch Linux"

  cecho "Partitioning the disk"
  parted -s $DISK \
    mklabel gpt \
    mkpart ESP 1MiB 256MiB \
    set 1 esp on \
    mkpart boot 256MiB 768MiB \
    mkpart root 768MiB 100%

  cecho "List the Partitions"
  fdisk -l

  cecho "Load the dm-crypt and dm-mod kernel module"
  modprobe dm-crypt
  modprobe dm-mod

  cecho "Encrypt the boot partition"
  cecho "Please provide the passphrase to encrypt the boot partition"
  cryptsetup luksFormat --type luks1 /dev/nvme0n1p2

  cecho "Open the encrypted boot partition"
  cecho "Please provide the passphrase to open the encrypted boot partition"
  cryptsetup open /dev/nvme0n1p2 luks_boot

  cecho "Encrypt the root partition"
  cecho "Please provide the passphrase to encrypt the root partition"
  cryptsetup luksFormat -v -s 512 -h sha512 /dev/nvme0n1p3

  cecho "Open the encrypted root partition"
  cecho "Please provide the passphrase to open the encrypted root partition"
  cryptsetup open /dev/nvme0n1p3 luks_root

  cecho "Format the Partitions"
  mkfs.vfat -n "EFI" /dev/nvme0n1p1
  mkfs.ext4 -L boot /dev/mapper/luks_boot
  mkfs.ext4 -L root /dev/mapper/luks_root

  cecho "Mount the Partitions"
  mount /dev/mapper/luks_root /mnt
  mkdir /mnt/boot
  mount /dev/mapper/luks_boot /mnt/boot
  mkdir /mnt/boot/efi
  mount /dev/nvme0n1p1 /mnt/boot/efi

  cecho "Install the linux packages"
  # pacman-key --refresh-keys
  pacman -S archlinux-keyring
  pacstrap -i /mnt base linux linux-firmware

  cecho "Generate the fstab configuration file"
  genfstab -U /mnt > /mnt/etc/fstab

  cecho "Copy the secureos script to chroot"
  cp -rpf /root/SecureOS/secureos /mnt/secureos
  chmod +x /mnt/secureos

  cecho "chroot into the '/mnt' and Run './secureos install-chroot'"

}

arch_install_after_chroot() {

  cecho "Install the necessary packages"
  pacman -S base-devel efibootmgr grub vim networkmanager git glibc wget

  cecho "Configure root password"
  cecho "Enter the password for root user"
  passwd

  cecho "Configure the locale settings"
  sed -i '/^#en_US.UTF-8 UTF-8/s/^#//' /etc/locale.gen
  locale-gen
  echo LANG=en_US.UTF-8 > /etc/locale.conf
  export LANG=en_US.UTF-8

  cecho "Configure the timezone settings"
  ln -sf /usr/share/zoneinfo/Asia/Dubai /etc/localtime
  hwclock --systohc --utc

  cecho "set hostname and hosts file"
  echo $HOSTNAME > /etc/hostname
  echo "127.0.0.1 localhost" > /etc/hosts
  echo "::1 localhost" >> /etc/hosts

  cecho "Configure GRUB settings with LUKS encryption"
  sed -i 's,GRUB_CMDLINE_LINUX="",GRUB_CMDLINE_LINUX="cryptdevice=/dev/nvme0n1p3:luks_root",g' /etc/default/grub
  sed -i '/^#GRUB_ENABLE_CRYPTODISK/s/^#//' /etc/default/grub

  cecho "Enable luks in mkinitcpio"
  sed -i '/^HOOKS/s/block /block encrypt /' /etc/mkinitcpio.conf
  mkinitcpio -p linux

  cecho "Install and configure the GRUB"
  grub-install --target=x86_64-efi --boot-directory=/boot --efi-directory=/boot/efi --bootloader-id=grub --recheck
  grub-mkconfig -o /boot/grub/grub.cfg

  cecho "It is necessary to unlock the boot partition without manual password request"
  dd bs=512 count=8 if=/dev/urandom of=/etc/key
  chmod 400 /etc/key
  cryptsetup luksAddKey /dev/nvme0n1p2 /etc/key
  echo "luks_boot /dev/nvme0n1p2 /etc/key luks" >> /etc/crypttab

  cecho "Some additional security"
  chmod 700 /boot

  cecho "Enable network manager"
  systemctl enable NetworkManager

  cecho "Press exit from chroot"

}

usb_auto_restart() {
  cecho "Copy the udev rules"
  cp auto-restart/85-remove-usb.rules /etc/udev/rules.d/
  cp auto-restart/solo-restart /usr/local/bin/
  chmod +x /usr/local/bin/solo-restart

  cecho "Reload the udev rules"
  udevadm control --reload-rules
  systemctl reload systemd-udevd
}

wipe_ram() {
  cecho "Setup the ArchStrike repository"
  echo "[archstrike]" >> /etc/pacman.conf
  echo "Server = https://mirror.archstrike.org/\$arch/\$repo" >> /etc/pacman.conf
  pacman -Syy

  cecho "Install the ArchStrike keyring"
  pacman-key --init
  dirmngr < /dev/null
  wget https://archstrike.org/keyfile.asc
  pacman-key --add keyfile.asc
  pacman-key --lsign-key 9D5F1C051D146843CDA4858BDE64825E7CBC0D51

  pacman -S archstrike-keyring
  pacman -S archstrike-mirrorlist
  sed -i 's,Server = https://mirror.archstrike.org/$arch/$repo,Include = /etc/pacman.d/archstrike-mirrorlist,g' /etc/pacman.conf
  pacman -Syy

  cecho "Install the secure-delete package"
  pacman -S secure-delete

  cecho "Copy the RAM wipe script"
  cp ram-wipe/shutdown_ramwipe /usr/local/bin/
  chmod +x /usr/local/bin/shutdown_ramwipe

  cecho "Configure the RAM wipe systemd service"
  cp ram-wipe/ram-wipe.service /usr/lib/systemd/system/
  systemctl daemon-reload
  systemctl enable ram-wipe.service
  systemctl start ram-wipe.service

}

random_mac() {
  cecho "Copy the configuration file"
  cp random-mac/random_mac.conf /etc/NetworkManager/conf.d/

  cecho "Reload the NetworkManager service"
  systemctl restart NetworkManager
}

uefi_secure_boot() {
  read -p "Did you enable the secure boot in BIOS settings? (yes / no): " secure

  if [ "$secure" == "yes" ]; then
    cecho "Install the secure boot tool"
    pacman -S efitools sbsigntools
    git clone https://github.com/saravanan30erd/secureboot
    cd secureboot
    make install

    cecho "Generate the UEFI secure boot keys"
    secureboot generate-keys
    cecho "Enrolling secure boot keys in UEFI firmware"
    secureboot enroll-keys
    cecho "Signing the boot loader with secure boot keys"
    secureboot sign-keys
    cecho "Verify the signed boot loader"
    secureboot verify-bootloader
    cd ../
  else
    cecho "!!! Please enable the secure boot in BIOS settings !!!"
    cecho "Refer here: https://github.com/saravanan30erd/secureboot"
    exit 1
  fi
}

boot_partition_tpm2luks() {
  read -p "Did you enable the TPM2.0 in BIOS settings? (yes / no): " success

  if [ "$success" == "yes" ]; then
    cecho "Install the tpm 2.0 tools"
    pacman -S tpm2-tools tpm2-tss tpm2-abrmd
    git clone https://github.com/saravanan30erd/tpm2luks
    cd tpm2luks
    make install

    sed -i 's,TPM2_LUKS_DEV="",TPM2_LUKS_DEV="/dev/nvme0n1p2",' /etc/tpm2luks.conf

    cecho "Print tpm2luks conf before proceed further"
    cat /etc/tpm2luks.conf

    read -p "Is it OK to proceed further? (yes / no): " proceed
    if [ "$proceed" == "yes" ]; then
      cecho "Enroll a secret key to existing LUKS encrypted volume using TPM 2.0"
      tpm2luks-enroll -d /dev/nvme0n1p2

      cecho "Enable tpm2luks in mkinitcpio"
      sed -i '/^HOOKS/s/encrypt /tpm2luks encrypt /' /etc/mkinitcpio.conf

      cecho "Regenerate the initramfs"
      tpm2luks-load
      cd ../
    fi
  else
    cecho "!!! Please enable the TPM2.0 in BIOS settings !!!"
    cecho "Refer here: https://github.com/saravanan30erd/tpm2luks"
    exit 1
  fi
}

root_partition_solokey() {
  cecho "Install the solokey dependency tool"
  pacman -S clang cargo git
  git clone https://github.com/shimunn/fido2luks
  cd fido2luks
  cargo install -f --path . --root /usr
  cd ../
  #rustup install stable
  #rustup default stable

  cecho "Install the solokey tool"
  git clone https://github.com/saravanan30erd/solokey-full-disk-encryption
  cd solokey-full-disk-encryption
  make install

  cecho "Configure the solokey configuration file"
  skfde-cred > cred.txt
  CREDENTIAL="$(cat cred.txt | grep 'SoloKey credential :' | awk '{print $4}')"
  sed -i "s,SKFDE_CREDENTIAL=\"\",SKFDE_CREDENTIAL=$CREDENTIAL," /etc/skfde.conf

  CHALLENGE="$(openssl rand -base64 12)"
  sed -i "s,SKFDE_CHALLENGE=\"\",SKFDE_CHALLENGE=$CHALLENGE," /etc/skfde.conf

  sed -i 's,SKFDE_LUKS_DEV="",SKFDE_LUKS_DEV="/dev/nvme0n1p3",' /etc/skfde.conf

  cecho "Print skfde conf before proceed further"
  cat /etc/skfde.conf

  read -p "Is it OK to proceed further? (yes / no): " success
  if [ "$success" == "yes" ]; then
    cecho "Enroll solokey passphrase to existing LUKS encrypted volume"
    skfde-enroll -d /dev/nvme0n1p3

    cecho "Enable skfde initramfs hook"
    sed -i '/^HOOKS/s/encrypt /skfde encrypt /' /etc/mkinitcpio.conf
    skfde-load
  else
    cecho "!!! Please check the skfde configuration !!!"
    exit 1
  fi
  cd ../
}

install_mate_xorg() {

  pacman -Sy
  pacman -S xorg

  cecho "Install the MATE desktop"
  pacman -S mate mate-extra

  cecho "Install the lightdm display server"
  pacman -S lightdm lightdm-gtk-greeter
  systemctl enable lightdm
}

## Main

case "$1" in
  install)
    arch_install_before_chroot;
    ;;
  install-chroot)
    arch_install_after_chroot;
    ;;
  usb-auto-reboot)
    usb_auto_restart;
    ;;
  ram-wipe)
    wipe_ram;
    ;;
  random-mac)
    random_mac;
    ;;
  secure-boot)
    uefi_secure_boot;
    ;;
  tpm2luks)
    boot_partition_tpm2luks;
    ;;
  solokey)
    root_partition_solokey;
    ;;
  install-ui)
    install_mate_xorg;
    ;;
  *)
    echo "  install     Arch Linux Installation with LUKS - Part 1"
    echo "  install-chroot     Arch Linux Installation with LUKS - Part 2"
    echo "  secure-boot    Enable Secure Boot in UEFI"
    echo "  usb-auto-reboot   Automatically reboot if any USB device is removed"
    echo "  ram-wipe    Wipe the RAM during shutdown and reboot"
    echo "  random-mac    Configure MAC address randomization"
    echo "  tpm2luks    Encrypt the boot partition using TPM 2.0"
    echo "  solokey   Encrypt the root partition using SoloKey"
    echo "  install-ui    Install the MATE desktop and lxdm display server"
    echo "  post-setup    Cleanup steps"
    ;;
esac
